# Why docker-compose
# 기본 도커 사용시 명령어에 이런 저런 옵션이 붙으면서 길어진다.
# 컨테이너간 연결, 통신을 해야하면 매우 길어진다.
# docker-compose 사용시 이러한 부분을 yml파일로 정의할 수 있기 때문에 실행이 간단해진다.

version: '3.2'

services:   
  web:
    image: nginx:latest
    container_name: web
    restart: "on-failure"
    ports:
      - 8090:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf/nginx.conf


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: "on-failure"
    expose:
      - 3000
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment: 
      - NODE_ENV=development 
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true


  backend:
    image: backend-spring
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8443:8443"  
    # [인증서 파일 저장 경로]:/root 
    volumes:
      # - /home/ubuntu/WISH/ssl:/root
      - /home/ubuntu/docker-volume/ssl:/root
    container_name: "backend"